// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchAndAsk(arg1, arg2) {
  return window['go']['main']['App']['SearchAndAsk'](arg1, arg2);
}

export function SelectAndIndexFolder() {
  return window['go']['main']['App']['SelectAndIndexFolder']();
}

export function StopSearch() {
  return window['go']['main']['App']['StopSearch']();
}
