// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';

export function SearchAndAsk(arg1:string,arg2:Array<llm.Message>):Promise<void>;

export function SelectAndIndexFolder():Promise<string>;

export function StopSearch():Promise<void>;
